### ISSUE TITLE
Consider rendering tips as XAML instead of HTML

### ISSUE THREAD

**Issue by AmadeusW** [justcla/HotTips#20]
We just discussed that the HTML renderer may be an overkill from the memory point of view.
As an optimization further into development process, let's consider a library such as [Markdown.XAML](https://github.com/theunrepentantgeek/Markdown.XAML)

**Comment by justcla** [comment]
I'd be keen to try it now. Does it render regular HTML and MD?
Is it any faster than the web control? Or is it just MD built on top of the existing web control?

**Comment by AmadeusW** [comment]
It builds bare WPF controls to render the MD. However, it does not render HTML embedded within MD.
It is faster because it does not load a web control and does not parse+render a website. What I'd be curious about is whether it would render images and gifs

**Comment by justcla** [comment]
Yes, it does render images. I like it a lot. I want to move to it. I played with it last night but failed to get it working in the project.

It takes simple MD (only), but I believe that is all we should need. We have simple mark-up. At most, we just need Bold and Links, and images.

I like the way links open in a new (external) web browser. Much cleaner that navigating inside the inbuilt web control.

**Comment by AmadeusW** [comment]
Great, I'll take care of adopting this library

**Comment by justcla** [comment]
Implemented in PR #26
